config/routes.rb
Mainteminderx::Application.routes.draw do


  resources :admin_objects


  get "log_out" => "sessions#destroy", :as => "log_out"
  get "delete_item" => "m_items#destroy", :as => "delete_item"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "bikes" => "bikes#index", :as => "bikes"

post "versions/:id/revert" => "versions#revert", :as => "revert_version"

root :to => "bikes#index"
get "/auth/:provider/callback" => "sessions#create"
post "/auth/identity/callback" => "sessions#create"
get "/auth/failure" => "sessions#failure" 


resources :users do
	post :set_admin
	post :unset_admin
	post :set_tester
	post :unset_tester
	post :destroy_by_admin
  post :enable_by_admin
end

resources :sessions

resources :identities

resources :bikes do
	get :import
	get :report
  get :dash
  member do
    get :graph
  end
end

resources :datalines do
  collection do
	  post :odo
  end
  
end

resources :pages

resources :m_items do
  post :complete
  collection { post :import }

end

get '/about' => 'pages#about'
get '/faqs' => 'pages#faqs'
get '/changelog' => 'pages#changelog'
get '/login' => 'pages#login'
get '/privacy' => 'pages#privacy'

get '/afaqs' => 'admin_objects#faqs'
get '/changes' => 'admin_objects#changes'
get '/text' => 'admin_objects#text'
get '/stats' => 'admin_objects#stats'

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
	has_many :bikes
  has_many :m_items, :through => :bikes
  has_many :datalines, :through => :bikes


  def update_picture(url)
    self.avatar = url 
    save!
  end

  def limit_reached
    @bikes = self.bikes.all
    total = @bikes.count
    if total >= self.limit
      return true
    else 
      return false
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.disabled_at = nil
      user.is_admin = false
      user.guess_on = true
      user.is_subscribed = true
      user.limit = 5
      user.avatar = "/images/user_icon.png"

      # test users can use beta features
      user.is_tester = false

      

      if auth["provider"] == "twitter"
        user.userid = auth["info"]["nickname"]
        user.name = auth["info"]["name"]
        user.email = ""
        user.avatar = auth["info"]["image"]
        
        if user.avatar == nil
          user.avatar = "/images/user_icon.png"
        end
      end
      
      if auth["provider"] = "facebook"
        user.userid = auth["info"]["nickname"]
        user.name = auth["info"]["name"]
        user.email = auth["info"]["email"]
        user.avatar = auth["info"]["image"]
        
        if user.avatar == nil
          user.avatar = "/images/user_icon.png"
        end
      end
      
      if auth["provider"] = "google_oauth2"
        user.userid = auth["info"]["nickname"]
        user.name = auth["info"]["name"]
        user.email = auth["info"]["email"]
        user.avatar = auth["info"]["image"]
        
        if user.avatar == nil
          user.avatar = "/images/user_icon.png"
        end
      end
      
      if auth["provider"] = "identity"
        user.name = auth["info"]["name"]
        user.email = auth["info"]["email"]
        
      end
      
    end
  end

  def overdueCount
    count = 0
    self.bikes.each do  |bike|
      count = count + bike.overcount
    end
    return count
  end

  def dueSoonCount
    count = 0
    self.bikes.each do  |bike|
      count = count + bike.dueSoonCount
    end
    return count
  end

  def self.weekly_mail
    users = User.all
    count = 0
    users.each do  |user|
      if user.id % 7 == (Time.zone.now.wday + 1)
        if user.email != "" && user.email != nil && user.is_subscribed == true && user.disabled_at == nil
          if user.overdueCount > 0 || user.dueSoonCount > 0
            MainDue.due(user).deliver
            count = count + 1
          end
        end
      end
    end
    MainDue.total_sent(count).deliver
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_filter :authenticate_user!, :only => [:create, :new]

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	    redirect_to new_session_path, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end

	def show
    	@user = current_user

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @user }
	    end
	  end

	def index
		unless current_user.is_admin?
	      session[:redirect] = request.fullpath
	      redirect_to bikes_path
	    end

    	@users = User.all

	    respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @user }
	    end
	  end

	def destroy
		@user = current_user
	  	@user.disabled_at = Time.zone.now
	  	@user.save
  		redirect_to new_session_path, :notice => "Account deleted, feel free to come back!"
	end

	def destroy_by_admin
		if current_user.is_admin?
			@user = User.find(params[:user_id])
		  	@user.disabled_at = Time.zone.now
		  	@user.save
	  		redirect_to users_path, :notice => "Account disabled"
	  	end
	end
  
	def enable_by_admin
		if current_user.is_admin?
			@user = User.find(params[:user_id])
		  	@user.disabled_at = nil
		  	@user.save
	  		redirect_to users_path, :notice => "Account enabled"
	  	end
	end

	def update
		@user = current_user
	    respond_to do |format|
	      if @user.update_attributes(user_params)
	        format.html { redirect_to bikes_path, notice: "User was successfully updated." }
	        format.json { head :no_content }
	      else
	        format.html { render action: "show" }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	def set_admin
		if current_user.is_admin?
			@user = User.find(params[:user_id])
			@user.is_admin = true
			@user.save
			redirect_to users_path, :notice => "User #" + @user.id.to_s + " is now an admin"
    else
      redirect_to users_path, :notice => "Nope! Only admins have such power."
		end
	end

	def unset_admin
		if current_user.is_admin?
			@user = User.find(params[:user_id])
			@user.is_admin = false
			@user.save
			redirect_to users_path, :notice => "User #" + @user.id.to_s + " is no longer an admin"
    else
      redirect_to users_path, :notice => "Nope! Only admins have such power."
		end
	end

	def set_tester
		if current_user.is_admin?
			@user = User.find(params[:user_id])
			@user.is_tester = true
			@user.save
			redirect_to users_path, :notice => "User #" + @user.id.to_s + " can now access test"
    else
      redirect_to users_path, :notice => "Nope! Only admins have such power."
		end
	end

	def unset_tester
		if current_user.is_admin?
			@user = User.find(params[:user_id])
			@user.is_tester = false
			@user.save
			redirect_to users_path, :notice => "User #" + @user.id.to_s + " can no longer access test"
    else
      redirect_to users_path, :notice => "Nope! Only admins have such power."
		end
	end
  
  private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, 
        :uid, :provider, :name, :avatar, :guess_on, :is_subscribed)
      end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
  <div class="field">
    <p>Name:  <%= @user.name %></p>
  </div>
  <div class="field">
    <p>Email:  <%= f.text_field :email, :class => 'input-large' %></p>
  </div>
  <div class="field">
    <% if @user.guess_on %>
    <p>Guess current odometer reading:   <%= f.check_box :guess_on, {:checked=>true} %></p>
    <% else %>
    <p>Guess current odometer reading:   <%= f.check_box :guess_on %></p>
    <% end %>
  </div>
  <div class="field">
    <% if @user.is_subscribed %>
    <p>Email me weekly maintenance report:   <%= f.check_box :is_subscribed, {:checked=>true} %></p>
    <% else %>
    <p>Email me weekly maintenance report:   <%= f.check_box :is_subscribed %></p>
    <% end %>
    <i>You will only recieve this email if maintenance is due within a week.</i>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-small" %>
  </div>
  </form>
<% end %>

app/views/users/index.html.erb
<h1>Admin console</h1>
<div class="span5">
  <ul class="nav nav-pills">
	  <li><a href="stats">Stats</a></li>
    <li>
    <a href="admin_objects">Bugs</a>
    </li>
    <li><a href="afaqs">FAQs</a></li>
    <li><a href="changes">Change Log</a></li>
    <li><a href="text">Site Text</a></li>
    <li class="active"><a href="users">Users</a></li>
  </ul>
</div>
<table class="table">
  <tr>
  	<th>id</th>
  	<th>Avatar</th>
    <th>Nickname</th>
    <th>Name</th>
    <th>email</th>
	<th>Limit</th>
    <th>Disabled date</th>
    <th>Tester</th>
    <th>Admin</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
    <tr>
    	<td><%= user.id %></td>
    	<td><%= image_tag user.avatar, :class => 'img-rounded', :size => "50x50" %></td>
	    <td><%= user.userid %></td>
	    <td><%= user.name %></td>
	    <td>
	    	<% if user.limit != nil %>
	    		<%= user.limit %>
	    	<%else%>
	    		<%= "No Limit" %>
	    	<%end%>	

	    </td>

	    <td>
	    	<% if user.email != nil && user.email != "" && user.email != "noemail" %>
	    		<%= user.email %>
	    	<%else%>
	    		<%= "No Email" %>
	    	<%end%>	

	    </td>
	    
	    <td>
	    	<% if user.disabled_at != nil %>
	    		<%= user.disabled_at %>
	    	<%else%>
	    		<%= "Enabled" %>
	    	<%end%>		    	

	    </td>
	    
	    <td>
	    	<% if user.is_tester %>
	    		<%= link_to 'Disable Testing', user_unset_tester_path(user), :class => 'btn btn-small' , :method => :post %>
	    	<%else%>
	    		<%= link_to 'Allow Testing', user_set_tester_path(user), :class => 'btn btn-small' , :method => :post %>
	    	<%end%>	
	    </td>
	    <td>
	    	<% if user.is_admin %>
	    		<%= link_to 'Disable Admin', user_unset_admin_path(user), :class => 'btn btn-small', :method => :post , data: { confirm: 'Are you sure?' } %>
	    	<%else%>
	    		<%= link_to 'Enable Admin', user_set_admin_path(user), :class => 'btn btn-small', :method => :post , data: { confirm: 'Are you sure?' } %>
	    	<%end%>	
	    </td>
	    <td>
	    	<% if user.disabled_at == nil %>
			<%= link_to 'Disable account', user_destroy_by_admin_path(user), :class => 'btn btn-small btn-danger', :method => :post, data: { confirm: 'Are you sure? Disabled accounts will be deleted in time.' } 
				    %>
	    	<%else%>
			<%= link_to 'Enable account', user_enable_by_admin_path(user), :class => 'btn btn-small btn-danger', :method => :post, data: { confirm: 'Are you sure?' } 
				    %>
	    	<%end%>	
	    </td>
    </tr>
  <% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
<h1>Account</h1>

<%= render 'form' %>

<div>
<%= link_to 'Delete My Account', @user, :class => 'btn btn-small btn-danger', method: :delete, data: { confirm: 'Are you sure, all bikes will be deleted?' } %>
</div>
</div>