config/routes.rb
Mainteminderx::Application.routes.draw do


  resources :admin_objects


  get "log_out" => "sessions#destroy", :as => "log_out"
  get "delete_item" => "m_items#destroy", :as => "delete_item"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "bikes" => "bikes#index", :as => "bikes"

post "versions/:id/revert" => "versions#revert", :as => "revert_version"

root :to => "bikes#index"
get "/auth/:provider/callback" => "sessions#create"
post "/auth/identity/callback" => "sessions#create"
get "/auth/failure" => "sessions#failure" 


resources :users do
	post :set_admin
	post :unset_admin
	post :set_tester
	post :unset_tester
	post :destroy_by_admin
  post :enable_by_admin
end

resources :sessions

resources :identities

resources :bikes do
	get :import
	get :report
  get :dash
  member do
    get :graph
  end
end

resources :datalines do
  collection do
	  post :odo
  end
  
end

resources :pages

resources :m_items do
  post :complete
  collection { post :import }

end

get '/about' => 'pages#about'
get '/faqs' => 'pages#faqs'
get '/changelog' => 'pages#changelog'
get '/login' => 'pages#login'
get '/privacy' => 'pages#privacy'

get '/afaqs' => 'admin_objects#faqs'
get '/changes' => 'admin_objects#changes'
get '/text' => 'admin_objects#text'
get '/stats' => 'admin_objects#stats'

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
	belongs_to :user
  has_many :m_items
  has_many :datalines
  has_paper_trail

  validates :year, :numericality => { :greater_than_or_equal_to => 1000, :less_than_or_equal_to => 9999 }
  validates :name, :presence => true
  validates :name, :length => { :maximum => 20 }
  validates :plate, :length => { :maximum => 20 }
  validates :colour, :length => { :maximum => 20 }
  validates :odo, :numericality => { :greater_than_or_equal_to => 0}
  
  def current_odo
  	odo = datalines.where(:datatype => "odometer").order("recorded_at DESC").first
    if odo == nil 
      return 1
    else
      return odo.value
    end
  end

  def overcount
  	count = 0
    	m_items.each do  |m_item| 

			if m_item.overdue? 
				count = count + 1
			end
		end
	return count
  end

  def dueSoonCount
    count = 0
      m_items.each do  |m_item| 

      if m_item.dueSoon? 
        count = count + 1
      end
    end
  return count
  end

  def odoGuess
      # Based on average of last 3 weeks odo readings.
      accuracy = 10 #higher the number better the guess but slower the read
      prev_line = nil
      odo_per_day = 0
      current = 0
      last_odo = 0
      last_odo_date = nil
      count = 0
      datalines.where(:datatype => "odometer").order("recorded_at DESC").first(accuracy).each do |line| 
        if count >= 1
          dif = line.value - prev_line.value
          time_dif = (line.recorded_at - prev_line.recorded_at).to_i / 1.day
          odo_per_day = odo_per_day + (dif / time_dif)
        else
          last_odo = line.value
          last_odo_date = line.recorded_at
        end
        count = count + 1
        prev_line = line
      end
      odo_per_day = odo_per_day / (count)
      p odo_per_day
      days_since = ((Time.now - last_odo_date).to_i / 1.day)
      if days_since < 1
        return last_odo.to_i 
      else
        return (last_odo + (odo_per_day * days_since)).to_i 
      end
  end
  
  def self.migrate_odo
    bikes = Bike.all
    bikes.each do |bike|
		  odo = bike.odo
      if odo != nil
        dataline = Dataline.create!
        dataline.value = odo
        dataline.recorded_at = Time.now
        dataline.datatype = 'odometer'
        dataline.bike_id = bike.id
        dataline.save!
      end
		  odo = bike.version_at(1.weeks.ago).odo
      if odo != nil
        dataline = Dataline.create!
        dataline.value = odo
        dataline.recorded_at = Time.now.ago(1.weeks)
        dataline.datatype = 'odometer'
        dataline.bike_id = bike.id
        dataline.save!
      end
		  odo = bike.version_at(2.weeks.ago).odo
      if odo != nil
        dataline = Dataline.create!
        dataline.value = odo
        dataline.recorded_at = Time.now.ago(2.weeks)
        dataline.datatype = 'odometer'
        dataline.bike_id = bike.id
        dataline.save!
      end
		  odo = bike.version_at(3.weeks.ago).odo
      if odo != nil
        dataline = Dataline.create!
        dataline.value = odo
        dataline.recorded_at = Time.now.ago(3.weeks)
        dataline.datatype = 'odometer'
        dataline.bike_id = bike.id
        dataline.save!
      end
    end
  end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bikes }
    end
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
    @bike = current_user.bikes.find(params[:id])
    @m_items = @bike.m_items.order("date ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bike }
    end
  end
  
  def dash
    @bike = current_user.bikes.find(params[:bike_id])
    @datalines = @bike.datalines.order("recorded_at DESC")

    respond_to do |format|
      format.html # dash.html.erb
      format.json { render json: @bike }
    end
  end
  
  # def graph
#       @bike = current_user.bikes.find(params[:bike_id])
#       @data1 = params[:data1]
#       @start = params[:start]
#       @finish = params[:finish]
#       
#       @series1 = current_user.bikes.map do |bike|
#             {
#               :key => @data1,
#               :values => bike.datalines.value.where(:bike_id => bike).order("recorded_at DESC")
#             }
#           end
#   end
  
  def report
    @bike = current_user.bikes.find(params[:bike_id])
    @m_items = @bike.m_items.order("date ASC")
    respond_to do |format|
      format.html {}
      format.json { render json: @bike }
    end
  end
  
  def import
  	if AdminObject.find_by_name("import_text").present?
  		@import_text = AdminObject.find_by_name("import_text").body
  	else
  		@import_text = ""
  	end
    @bike = current_user.bikes.find(params[:bike_id])
    respond_to do |format|
      format.html # import.html.erb
      format.json { render json: @bike }
    end
  end

  # GET /bikes/new
  # GET /bikes/new.json
  def new
    if ( !current_user.limit.present? || !current_user.limit_reached )
      @bike = Bike.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @bike }
      end
    else
      format.html { render action: "index", notice: "You have already reached your vehicle limit."}
    end
  end

  # GET /bikes/1/edit
  def edit
    @bike = current_user.bikes.find(params[:id])
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = current_user.bikes.build(bike_params)
    
    # @bike = Bike.new(bike_params)
#     @bike.user_id = current_user.id

    respond_to do |format|
      if @bike.save
        @bike.datalines.new_odo(@bike)
        format.html { redirect_to @bike, notice: "Vehicle was successfully created."}
        format.json { render json: @bike, status: :created, location: @bike }
      else
        format.html { render action: "new" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bikes/1
  # PUT /bikes/1.json
  def update
    @bike = current_user.bikes.find(params[:id])

    respond_to do |format|
      if @bike.update_attributes(bike_params)
        @bike.datalines.new_odo(@bike)
        format.html { redirect_to @bike, notice: "Vehicle was successfully updated. #{undo_link}" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike = current_user.bikes.find(params[:id])
    @bike.destroy

    respond_to do |format|
      format.html { redirect_to bikes_url, notice: "Vehicle was successfully deleted. #{undo_link}" }
      format.json { head :no_content }
    end
  end


  def undo_link
    view_context.link_to("undo", revert_version_path(@bike.versions.scoped.last), :method => :post)
  end

  private
      # Use callbacks to share common setup or constraints between actions.
      def set_bike
        @bike = Bike.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def bike_params
        params.require(:bike).permit(:name, :odo, :plate, :colour, :year, :picurl)
      end

end

app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
  <p>* = required</p>
  <div class="control-group">
    <label class="control-label" for="inputName">Name *</label>
     <div class="controls">
    <%= f.text_field :name, :class => 'input-large', :id => "inputName" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputColour">Year *</label>
     <div class="controls">
    <%= f.text_field :year, :class => 'input-small', :id => "inputColour" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputOdo">Odometer *</label>
     <div class="controls">
    <%= f.text_field :odo, :class => 'input-small', :id => "inputOdo" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPlate">Plate</label>
     <div class="controls">
    <%= f.text_field :plate, :class => 'input-small', :id => "inputPlate" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputColour">Colour</label>
     <div class="controls">
    <%= f.text_field :colour, :class => 'input-small', :id => "inputColour" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputColour">Photo - Enter the URL of a hosted photo for your bike.</label>
     <div class="controls">
    <%= f.text_field :picurl, :class => 'input-large', :id => "inputColour" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-small' %>
  </div>
  </form>
<% end %>

app/views/bikes/_update_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
  <p>* = required</p>
  <div class="control-group">
    <label class="control-label" for="inputName">Name *</label>
     <div class="controls">
    <%= f.text_field :name, :class => 'input-large', :id => "inputName" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputColour">Year *</label>
     <div class="controls">
    <%= f.text_field :year, :class => 'input-small', :id => "inputColour" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPlate">Plate</label>
     <div class="controls">
    <%= f.text_field :plate, :class => 'input-small', :id => "inputPlate" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputColour">Colour</label>
     <div class="controls">
    <%= f.text_field :colour, :class => 'input-small', :id => "inputColour" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputColour">Photo - Enter the URL of a hosted photo for your bike.</label>
     <div class="controls">
    <%= f.text_field :picurl, :class => 'input-large', :id => "inputColour" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-small' %>
  </div>
  </form>
<% end %>

app/views/bikes/_update_odo_form.html.erb
<%= form_for(bike) do |f| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="inputOdo"><strong>Odometer</strong></label>
     <div class="controls">
    <%= f.text_field :odo, :class => 'input-small', :id => "inputOdo", :placeholder => bike.current_odo %>
    </div>
  </div>
  <div class="actions">
      <%= f.submit "Update Odometer", :class => 'btn btn-small' %>
      <%= link_to "View", bike, :class => 'btn btn-small' %>
    </div>
  </form>
<% end %>

app/views/bikes/dash.html.erb
<div class="container-fluid">
	<div class="span12">
	  <h2><%= @bike.name %></h2>
	</div>
	<div class="span2">
	    <% if @bike.picurl != nil && @bike.picurl != ""%>
	    <%= image_tag @bike.picurl, :class => 'img-rounded', :size => "200x200" %>
	    <%end%>
	</div>
	<div class="span4">
	<ul>
	  <b>Year:</b>
	  <%= @bike.year %>
	</ul>
	<ul>
	  <b>Odometer:</b>
	  <%= @bike.current_odo %>
	</ul>
	<ul>
	  <b>Plate:</b>
	  <%= @bike.plate %>
	</ul>
	<ul>
	  <b>Colour:</b>
	  <%= @bike.colour %>
	</ul>
	</div>
	<div class="span12">
		<%if current_user.is_tester? %>
      <ul class="nav nav-pills">
		<li class="active"><%= link_to 'Refresh', '#'%></li>      
		<li class="disabled"><%= link_to '', '' %></li>
		<li class="dropdown, active">
		    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
		      Data 1 <span class="caret"></span>
		    </a>
		    <ul class="dropdown-menu">
		      
				  <% @bike.datalines.select("DISTINCT(datatype)").each do |line| %>
				  <li>
				  	<%= link_to line.datatype, '#'%>
				  </li>
				  <% end %>
		      
		    </ul>
		</li>
		<li class="dropdown, active">
		    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
		      Data 2 <span class="caret"></span>
		    </a>
		    <ul class="dropdown-menu">
			  <% @bike.datalines.select("DISTINCT(datatype)").each do |line| %>
			  <li>
			  	<%= link_to line.datatype, '#'%>
			  </li>
			  <% end %>
		      
		    </ul>
		</li>
		<li class="dropdown, active">
		    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
		      Data 3 <span class="caret"></span>
		    </a>
		    <ul class="dropdown-menu">
			  <% @bike.datalines.select("DISTINCT(datatype)").each do |line| %>
			  <li>
			  	<%= link_to line.datatype, '#'%>
			  </li>
			  <% end %>
		      
		    </ul>
		</li>
		<li class="disabled"><%= link_to '', '' %></li>
		<li class="active">
			  <div id="datetimepicker1" class="input-append date">
			    <input data-format="dd/MM/yyyy hh:mm:ss" type="text"></input>
			    <span class="add-on">
			      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
			      </i>
			    </span>
			  </div>
			<script type="text/javascript">
			  $(function() {
			    $('#datetimepicker1').datetimepicker({
			      language: 'pt-BR'
			    });
			  });
			</script>
		</li>
		<li> <strong> to </strong> </li>
		<li class="active">
			  <div id="datetimepicker1" class="input-append date">
			    <input data-format="dd/MM/yyyy hh:mm:ss" type="text"></input>
			    <span class="add-on">
			      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
			      </i>
			    </span>
			  </div>
			<script type="text/javascript">
			  $(function() {
			    $('#datetimepicker1').datetimepicker({
			      language: 'pt-BR'
			    });
			  });
			</script>
		</li>
		<li class="disabled"><%= link_to '', '' %></li>
		<li class="active"><%= link_to 'Exit Dash', bike_path(@bike)%></li>
      </ul>
    </div>
	<script>
	nv.addGraph(function () {
	    var chart = nv.models.linePlusBarChart().margin({
	        top: 30,
	        right: 20,
	        bottom: 50,
	        left: 45
	    }).showLegend(true).tooltipContent(function (key, y, e, graph) {
	        return '<h3>' + key + '</h3>' + '<p>' + e + '% at ' + y + '</p>'
	    });
    
	    //chart.forceY([3, 5]);
    
	    chart.xAxis.tickFormat(function (d) {
	        //return d3.time.format('%x')(new Date(d))
	        //return d3.time.format('%H:%M:%S')(new Date(d))
	        return d3.time.format('%d/%m/%y')(new Date(d))
	    });

	    d3.select('#lineChart svg')
	        .datum(data)
	        .transition().duration(500)
	        .call(chart);

	    nv.utils.windowResize(chart.update);
	    return chart;
	});

	data = [{
	    "values": [{
	        "x": 1025409600000 ,
	            "y": 3.5
	    }, {
	        "x": 1028088000000 ,
	            "y": 4
	    }, {
	        "x": 1030766400000 ,
	            "y": 3.9
	    }, {
	        "x": 1033358400000 ,
	            "y": 3
	    }, {
	        "x": 1036040400000  ,
	            "y": 3.8
	    }, {
	        "x": 1038632400000  ,
	            "y": 3.7
	    }],
	        "key": "Sine Wave",
	}]
	
	</script>
	
	<div id="lineChart">
	    <svg></svg>
	</div>

  	  <%end%>
</div>

app/views/bikes/edit.html.erb
<div class="container-fluid">
<h1>Editing <%= @bike.name %></h1>

<%= render 'update_form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>
</div>

app/views/bikes/import.html.erb
<div class="container-fluid">
	<div class="span12">
		<h2>Import Maintenance Items</h2>
        <p><% if @import_text.present? %> 
        	<%= markdown(@import_text) %>
        	<% end %>
        	 </p>
	</div>
	<div class="span12">
		<%= form_tag import_m_items_path(:bike_id => @bike), multipart: true do %>
	  		<%= file_field_tag :file %>
	  		<%= submit_tag "Import", :class => 'btn btn-small' %>
		<% end %>
	</div>
</div>

app/views/bikes/index.html.erb
<% if current_user %>

<% if current_user.email == "" %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Warning!</strong> 
    You have not added an email address, you will not recieve email notifications.
  </div>
<%end%>
<div class="container-fluid">
<div class="span6 offset2">
<h4>Your Vehicles</h4>
<%= link_to 'New Vehicle', new_bike_path, :class => 'btn btn-small' %>
 </div>
 <div>
  <BR>&nbsp;<BR>
 <% if current_user.bikes.count > 0 %>
  <% current_user.bikes.each do |bike| %>
    <div class="row-fluid">
      <div class="span6 offset3">
        <div class="hero-unit">
        
          <% if bike.overcount > 0 %>
            <span class="badge badge-info pull-right"><%= bike.overcount %></span>
          <%end%>

          
          <% if bike.picurl != nil && bike.picurl != ""%>
          <h1><%= link_to (image_tag bike.picurl, :class => 'img-rounded', :size => "100x100"), bike %>
            <%= bike.name %></h1>
          <% else %>
          <h1><%= bike.name %></h1>
          <%end%>
          <br>
		  	<%= render :partial => "datalines/new_odo_form", :locals => { :dataline => bike.datalines.new, :bike => bike } %>
          
          
        </div>
    </div>
    </div>  
  <% end %>
<% else %>
<p> You have no vehicles! </p>

<% end %>
</div>
</div>

<% end %>

app/views/bikes/new.html.erb
<div class="container-fluid">
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>
</div>

app/views/bikes/report.html.erb
<div class="container-fluid">
	<div class="span12">
	  <h1>Maintenance Report</h1>
	</div>
	<div class="span12">
	  <h2><%= @bike.name %></h2>
	</div>
<div class="span2">
    <% if @bike.picurl != nil && @bike.picurl != ""%>
    <%= image_tag @bike.picurl, :class => 'img-rounded', :size => "200x200" %>
    <%end%>
</div>
<div class="span4">
<ul>
  <b>Year:</b>
  <%= @bike.year %>
</ul>
<ul>
  <b>Odo:</b>
  <%= @bike.odo %>
</ul>
<ul>
  <b>Plate:</b>
  <%= @bike.plate %>
</ul>
<ul>
  <b>Colour:</b>
  <%= @bike.colour %>
</ul>
</div>
<div class="span12">
<table class="table">
	<tr>
		<td>Maintenance Item</td>
		<td>Completed on</td>
		<td>Odometer reading</td>
	    <td>Notes</td>
	</tr>

	<% @bike.m_items.sort_by!%>
<% @bike.m_items.each do |m_item| %>
	<% if m_item.completed_at.present? %>
 	<tr class="info">
 		<td><%= m_item.name %></td>
		<td><%= m_item.completed_at %></td>
		<td><%= m_item.completed_at_odo %></td>
	    <td><%= m_item.notes %></td>
	</tr>
	<% end %>
<% end %>
</table>
</div>
</div>

app/views/bikes/show.html.erb
<div class="container-fluid">
	<div class="span12">
	  <h2><%= @bike.name %></h2>
	</div>
<div class="span2">
    <% if @bike.picurl != nil && @bike.picurl != ""%>
    <%= image_tag @bike.picurl, :class => 'img-rounded', :size => "200x200" %>
    <%end%>
</div>
<div class="span4">
<ul>
  <b>Year:</b>
  <%= @bike.year %>
</ul>
<ul>
  <b>Odometer:</b>
  <%= @bike.current_odo.round %>
</ul>
<ul>
  <b>Plate:</b>
  <%= @bike.plate %>
</ul>
<ul>
  <b>Colour:</b>
  <%= @bike.colour %>
</ul>
</div>
    <div class="span12">
      <ul class="nav nav-pills">      
		<li class="active"><%= link_to 'New Maintenance Item', new_m_item_path(:bike_id => @bike) %></li>
		<li class="active"><%= link_to 'Import Maintenance Items', bike_import_path(@bike) %></li>
		<li class="active"><%= link_to 'View Maintenance Report', bike_report_path(@bike), :target => "_blank" %></li>
		<% if current_user.is_tester? %>
			<li class="active"><%= link_to 'Dash', bike_dash_path(@bike) %></li>
		<% end %>
		<li class="disabled"><%= link_to '', '' %></li>
        <li class="active"><%= link_to 'Edit Vehicle', edit_bike_path(@bike) %></li>        
		<li class="active"><%= link_to 'Delete Vehicle', @bike, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
<div>
<table class="table">
	<tr>
		<td>Maintenance Item</td>
	    <td>Odometer due</td>
	    <td>Date due</td>
	    <td>Notes</td>
		<td>Complete?</td>
	    <td>Delete?</td>
	</tr>

	<% @bike.m_items.sort_by!%>
<% @bike.m_items.each do |m_item| %>
	<% if m_item.overdue? && !m_item.completed_at.present? %>
 	<tr class="error">
 		<td><%= m_item.name %></td>
	    <td><%= m_item.odo %></td>
	    <td><%= m_item.date %></td>
	    <td><%= m_item.notes %></td>
		<td><%= link_to 'Complete', m_item_complete_path(m_item), :class => 'btn btn-small btn-info', :method => :post, data: { confirm: 'Are you sure?' } %></td>
	    <td><%= link_to 'Delete', m_item, :class => 'btn btn-small btn-danger', method: :delete %></td>
	</tr>
	<% end %>
 	
<% end %>
<% @bike.m_items.each do |m_item| %>
<% if !m_item.overdue? && !m_item.completed_at.present? %>
 	<tr class="info">
		<td><%= m_item.name %></td>
	    <td><%= m_item.odo %></td>
	    <td><%= m_item.date %></td>
	    <td><%= m_item.notes %></td>
		<td><%= link_to 'Complete', m_item_complete_path(m_item), :class => 'btn btn-small btn-info', :method => :post, data: { confirm: 'Are you sure?' } %></td>
	    <td><%= link_to 'Delete', m_item, :class => 'btn btn-small btn-danger', method: :delete %></td>
	</tr>
	<% end %>
	<% end %>
</table>
</div>
</div>