config/routes.rb
Mainteminderx::Application.routes.draw do


  resources :admin_objects


  get "log_out" => "sessions#destroy", :as => "log_out"
  get "delete_item" => "m_items#destroy", :as => "delete_item"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "bikes" => "bikes#index", :as => "bikes"

post "versions/:id/revert" => "versions#revert", :as => "revert_version"

root :to => "bikes#index"
get "/auth/:provider/callback" => "sessions#create"
post "/auth/identity/callback" => "sessions#create"
get "/auth/failure" => "sessions#failure" 


resources :users do
	post :set_admin
	post :unset_admin
	post :set_tester
	post :unset_tester
	post :destroy_by_admin
  post :enable_by_admin
end

resources :sessions

resources :identities

resources :bikes do
	get :import
	get :report
  get :dash
  member do
    get :graph
  end
end

resources :datalines do
  collection do
	  post :odo
  end
  
end

resources :pages

resources :m_items do
  post :complete
  collection { post :import }

end

get '/about' => 'pages#about'
get '/faqs' => 'pages#faqs'
get '/changelog' => 'pages#changelog'
get '/login' => 'pages#login'
get '/privacy' => 'pages#privacy'

get '/afaqs' => 'admin_objects#faqs'
get '/changes' => 'admin_objects#changes'
get '/text' => 'admin_objects#text'
get '/stats' => 'admin_objects#stats'

end

app/models/admin_object.rb
class AdminObject < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
end

app/controllers/admin_objects_controller.rb
class AdminObjectsController < ApplicationController
  
  before_filter :authenticate_admin!

  def authenticate_admin!
    unless current_user.is_admin?
      session[:redirect] = request.fullpath
      redirect_to bikes_path
    end
  end

  def index
    @admin_objects = AdminObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_objects }
    end
  end

  def changes
    @admin_objects = AdminObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_objects }
    end
  end

  def faqs
    @admin_objects = AdminObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_objects }
    end
  end

  def text
    @admin_objects = AdminObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_objects }
    end
  end
  
  def stats
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /admin_objects/1
  # GET /admin_objects/1.json
  def show
    @admin_object = AdminObject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_object }
    end
  end

  # GET /admin_objects/new
  # GET /admin_objects/new.json
  def new
    @admin_object = AdminObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_object }
    end
  end

  # GET /admin_objects/1/edit
  def edit
    @admin_object = AdminObject.find(params[:id])
  end

  # POST /admin_objects
  # POST /admin_objects.json
  def create
    @admin_object = AdminObject.new(admin_object_params)

    respond_to do |format|
      if @admin_object.save
        format.html { redirect_to @admin_object, notice: 'Admin object was successfully created.' }
        format.json { render json: @admin_object, status: :created, location: @admin_object }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin_objects/1
  # PUT /admin_objects/1.json
  def update
    @admin_object = AdminObject.find(params[:id])

    respond_to do |format|
      if @admin_object.update_attributes!(admin_object_params)
        format.html { redirect_to @admin_object, notice: 'Admin object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_objects/1
  # DELETE /admin_objects/1.json
  def destroy
    @admin_object = AdminObject.find(params[:id])
    @admin_object.destroy

    respond_to do |format|
      format.html { redirect_to admin_objects_url }
      format.json { head :no_content }
    end
  end
  
  private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_object
        @admin_object = AdminObject.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def admin_object_params
        params.require(:admin_object).permit(:name, :body, :date_created, :object_type, :priority, :answer)
      end
end

app/helpers/admin_objects_helper.rb
module AdminObjectsHelper
end

app/views/admin_objects/_form.html.erb
<%= form_for(@admin_object) do |f| %>
  <% if @admin_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_object.errors.count, "error") %> prohibited this admin_object from being saved:</h2>

      <ul>
      <% @admin_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :date_created %>
    <%= f.date_select :date_created %>
  </div>
  <div class="field">
    <%= f.label :object_type %>
    <select name="admin_object[object_type]">
      <option value="bug" selected="selected">Bug</option>
      <option value="question">FAQ</option>
      <option value="text">Site Text</option>
      <option value="change">Change</option>
    </select>
   
  </div>
  <div class="field">
    <%= f.label :priority %>
    <%= f.text_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin_objects/changes.html.erb
<h1>Admin console</h1>
  <div class="span5">
    <ul class="nav nav-pills">
		<li><a href="stats">Stats</a></li>
      <li>
      <a href="admin_objects">Bugs</a>
      </li>
      <li><a href="afaqs">FAQs</a></li>
      <li class="active"><a href="changes">Change Log</a></li>
      <li><a href="text">Site Text</a></li>
      <li><a href="users">Users</a></li>
    </ul>
  </div>
  <div class="span3 pull-right">
    <%= link_to 'Log New Changes', new_admin_object_path, :class => 'btn btn-small' %>
  </div>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Date created</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_objects.each do |admin_object| %>
<% if admin_object.object_type == 'change' %>
  <tr>
    <td><%= admin_object.name %></td>
    <td><%= admin_object.body %></td>
    <td><%= admin_object.date_created %></td>
    <td><%= link_to 'Show', admin_object %></td>
    <td><%= link_to 'Edit', edit_admin_object_path(admin_object) %></td>
    <td><%= link_to 'Destroy', admin_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

app/views/admin_objects/edit.html.erb
<h1>Editing admin_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_object %> |
<%= link_to 'Back', admin_objects_path %>

app/views/admin_objects/faqs.html.erb
<h1>Admin console</h1>
<div class="span5">
  <ul class="nav nav-pills">
	  <li><a href="stats">Stats</a></li>
    <li>
    <a href="admin_objects">Bugs</a>
    </li>
    <li class="active"><a href="afaqs">FAQs</a></li>
    <li><a href="changes">Change Log</a></li>
    <li><a href="text">Site Text</a></li>
    <li><a href="users">Users</a></li>
  </ul>
</div>
<div class="span3 pull-right">
  <%= link_to 'New FAQ', new_admin_object_path, :class => 'btn btn-small' %>
</div>

<table class="table">
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_objects.each do |admin_object| %>
  <% if admin_object.object_type == 'question' %>
    <tr>
      <td><%= admin_object.name %></td>
      <td><%= admin_object.body %></td>
      <td><%= link_to 'Show', admin_object %></td>
      <td><%= link_to 'Edit', edit_admin_object_path(admin_object) %></td>
      <td><%= link_to 'Destroy', admin_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

app/views/admin_objects/index.html.erb
<h1>Admin console</h1>
<div>
    <div class="span5">
        <ul class="nav nav-pills">
			<li><a href="stats">Stats</a></li>
          <li class="active">
          <a href="admin_objects">Bugs</a>
          </li>
          <li><a href="afaqs">FAQs</a></li>
          <li><a href="changes">Change Log</a></li>
          <li><a href="text">Site Text</a></li>
          <li><a href="users">Users</a></li>
        </ul>
    </div>
    <div class="span3 pull-right">
    <%= link_to 'Log New Bug', new_admin_object_path, :class => 'btn btn-small' %>
    </div>
</div>
<table class="table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Info</th>
    <th>Date logged</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_objects.each do |admin_object| %>
<% if admin_object.object_type == 'bug' %>
  <tr>
    <td><%= admin_object.id %></td>
    <td><%= admin_object.name %></td>
    <td><%= admin_object.body %></td>
    <td><%= admin_object.date_created %></td>
    <td><%= admin_object.priority %></td>
    <td><%= link_to 'Show', admin_object %></td>
    <td><%= link_to 'Edit', edit_admin_object_path(admin_object) %></td>
    <td><%= link_to 'Destroy', admin_object, method: :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

app/views/admin_objects/new.html.erb
<div class="span4">
<h1>New Bug, FAQ or Site Text</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_objects_path %>
</div>

app/views/admin_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_object.name %>
</p>

<p>
  <b>Body:</b>
  <%= @admin_object.body %>
</p>

<p>
  <b>Date created:</b>
  <%= @admin_object.date_created %>
</p>

<p>
  <b>Type:</b>
  <%= @admin_object.object_type %>
</p>

<p>
  <b>Priority:</b>
  <%= @admin_object.priority %>
</p>

<p>
  <b>Answer:</b>
  <%= @admin_object.answer %>
</p>


<%= link_to 'Edit', edit_admin_object_path(@admin_object) %> |
<%= link_to 'Back', admin_objects_path %>

app/views/admin_objects/stats.html.erb
<h1>Admin console</h1>
  <div class="span5">
    <ul class="nav nav-pills">
		<li class="active"><a href="stats">Stats</a></li>
      <li>
      <a href="admin_objects">Bugs</a>
      </li>
      <li><a href="afaqs">FAQs</a></li>
      <li><a href="changes">Change Log</a></li>
      <li><a href="text">Site Text</a></li>
      <li><a href="users">Users</a></li>
    </ul>
  </div>

<table class="table">
  <tr>
    <td>Users</td>
    <td><%= User.count %></td>
  </tr>
  <tr>
    <td>Vehicles</td>
    <td><%= Bike.count %></td>
  </tr>
  <tr>
    <td>Twitter Users</td>
    <td><%= User.where(provider: "twitter").count %></td>
  </tr>
  <tr>
    <td>Facebook Users</td>
    <td><%= User.where(provider: "facebook").count %></td>
  </tr>
  <tr>
    <td>Google Users</td>
    <td><%= User.where(provider: "google_oauth2").count %></td>
  </tr>
  <tr>
    <td>Local Users</td>
    <td><%= User.where(provider: "identity").count %></td>
  </tr>
</table>

<br />

app/views/admin_objects/text.html.erb
<h1>Admin console</h1>
<div class="span5">
  <ul class="nav nav-pills">
    <li>
    <a href="admin_objects">Bugs</a>
    </li>
    <li><a href="afaqs">FAQs</a></li>
    <li><a href="changes">Change Log</a></li>
    <li class="active"><a href="text">Site Text</a></li>
    <li><a href="users">Users</a></li>
  </ul>
</div>
<div class="span3 pull-right">
  <%= link_to 'Create new text', new_admin_object_path, :class => 'btn btn-small' %>
</div>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Last Modified</th>
    <th></th>
  </tr>

<% @admin_objects.each do |admin_object| %>
<% if admin_object.object_type == 'text' %>
  <tr>
    <td><%= admin_object.name %></td>
    <td><%= admin_object.body %></td>
    <td><%= admin_object.date_created %></td>
    <td><%= link_to 'Edit', edit_admin_object_path(admin_object) %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />