config/routes.rb
Mainteminderx::Application.routes.draw do


  resources :admin_objects


  get "log_out" => "sessions#destroy", :as => "log_out"
  get "delete_item" => "m_items#destroy", :as => "delete_item"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "bikes" => "bikes#index", :as => "bikes"

post "versions/:id/revert" => "versions#revert", :as => "revert_version"

root :to => "bikes#index"
get "/auth/:provider/callback" => "sessions#create"
post "/auth/identity/callback" => "sessions#create"
get "/auth/failure" => "sessions#failure" 


resources :users do
	post :set_admin
	post :unset_admin
	post :set_tester
	post :unset_tester
	post :destroy_by_admin
  post :enable_by_admin
end

resources :sessions

resources :identities

resources :bikes do
	get :import
	get :report
  get :dash
  member do
    get :graph
  end
end

resources :datalines do
  collection do
	  post :odo
  end
  
end

resources :pages

resources :m_items do
  post :complete
  collection { post :import }

end

get '/about' => 'pages#about'
get '/faqs' => 'pages#faqs'
get '/changelog' => 'pages#changelog'
get '/login' => 'pages#login'
get '/privacy' => 'pages#privacy'

get '/afaqs' => 'admin_objects#faqs'
get '/changes' => 'admin_objects#changes'
get '/text' => 'admin_objects#text'
get '/stats' => 'admin_objects#stats'

end

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41368407-1', 'mainteminder.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MainteMinder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <a class="brand" href="/bikes">MainteMinder</a>
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <ul class="pull-right">
            <% if current_user %>
                <h8><%= current_user.name %></h8>
                <% if current_user.avatar %>
                  <%= link_to image_tag(current_user.avatar, :height => '32', :width => '32'), current_user%>
                <% end %>
            <% else %>
                <strong>
                  Sign in <i class="icon-hand-right"></i>
                </strong>
                <%= link_to image_tag("/images/twitter-icon.png"), "/auth/twitter" %>
                <%= link_to image_tag("/images/facebook-icon.png"), "/auth/facebook" %>
                <%= link_to image_tag("/images/google-icon.png"), "/auth/google_oauth2" %>
                

          <% end %>
        </ul>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <% if current_user && user_enabled? %>
              <% if params[:controller] == 'bikes' %>
                <li class="active" ><%= link_to "Vehicles", bikes_path %></li>
              <% else %>
                <li><%= link_to "Vehicles", bikes_path %></li>
              <% end %>
              <% if params[:controller] == 'users' %>
                <li class="active" ><%= link_to "Account", current_user %></li>
              <% else %>
                <li><%= link_to "Account", current_user %></li>
              <% end %>
              <% if params[:controller] == 'pages' %>
                <li class="active" ><%= link_to "Help", "/faqs" %></li>
              <% else %>
                <li><%= link_to "Help", "/faqs" %></li>
              <% end %>
              <% if current_user.is_admin == true %>
                <% if params[:controller] == 'admin_objects' %>
                  <li class="active" ><%= link_to "Admin", admin_objects_path %></li>
                <% else %>
                  <li><%= link_to "Admin", stats_path %></li>
                <% end %>
              <% end %>
              <li><%= link_to "Sign out", log_out_path %></li>
            <% else %>
              <% if params[:controller] == 'pages' %>
                <li class="active" ><%= link_to "About", '/about' %></li>
              <% else %>
                <li><%= link_to "About", '/about' %></li>
              <% end %>   
            <% end %>
          </ul>
        </div>
    </div>
  </div> 
  <% if current_user && !user_enabled? %>
    <div class="alert alert-error">
    Your account is disabled, contact support. 
    </div>
  <% end %>
<% flash.each do |name, msg| %>
<div class="alert alert-info">
<button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= raw(msg) %>
</div>
<% end %>

<%= yield %>
<%= render :partial => 'layouts/ga' if Rails.env == 'production' %>
</body>
</html>